import { expect, test } from '@playwright/test';

test('combines request filters, includes date boundaries and clears empty results', async ({ page, request }) => {
  await request.post('http://127.0.0.1:4401/reset');
  await page.goto('/login');
  await page.getByLabel('Usuario', { exact: true }).fill('admin-test');
  await page.getByLabel('Contraseña', { exact: true }).fill('test-password-only');
  await page.getByRole('button', { name: 'Ingresar al panel' }).click();
  await expect(page.getByRole('heading', { name: 'Resumen general' })).toBeVisible();
  const create = async (resource: string, data: object) => {
    const response = await page.request.post('/api/manage/' + resource, { headers: { origin: 'http://localhost:3101' }, data });
    expect(response.status()).toBe(201);
    return response.json();
  };
  const club = await create('venues', { name: 'Club Centro', isActive: true });
  const otherClub = await create('venues', { name: 'Club Sur', isActive: false });
  const tennis = await create('sports', { name: 'Tenis', isActive: true });
  const football = await create('sports', { name: 'Fútbol', isActive: true });
  await create('booking-drafts', { renterFirstName: 'Ana', venueId: club.id, sportId: tennis.id, date: '2099-01-10', status: 'PENDING_CONFIRMATION' });
  await create('booking-drafts', { renterFirstName: 'Bruno', venueId: otherClub.id, sportId: football.id, date: '2099-01-11', status: 'CONFIRMED' });
  await create('booking-drafts', { renterFirstName: 'Carla', venueId: club.id, sportId: football.id, date: '2099-01-10', status: 'CONFIRMED' });
  await create('booking-drafts', { renterFirstName: 'Diana', venueId: club.id, sportId: tennis.id });
  await create('booking-drafts', { renterFirstName: 'Elena', venueId: club.id, sportId: football.id, date: '2099-01-10', status: 'CONFIRMED', paymentStatus: 'TOTAL_PAID' });
  await page.reload();
  await page.getByRole('navigation').getByRole('button', { name: /Solicitudes/ }).click();
  const cell = (name: string) => page.getByRole('cell', { name, exact: true });
  await expect(cell('Diana')).toBeVisible();
  await page.getByLabel('Estado de solicitud').selectOption('PENDING');
  await expect(cell('Ana')).toBeVisible();
  await expect(cell('Diana')).toBeVisible();
  await expect(cell('Bruno')).toHaveCount(0);
  await page.getByLabel('Sede de solicitud').selectOption(club.id);
  await page.getByLabel('Deporte de solicitud').selectOption(tennis.id);
  await page.getByLabel('Fecha del turno desde').fill('2099-01-10');
  await page.getByLabel('Fecha del turno hasta').fill('2099-01-10');
  await expect(cell('Ana')).toBeVisible();
  await expect(cell('Diana')).toHaveCount(0);
  await expect(page.locator('.count')).toHaveText('1 registros');
  await page.getByLabel('Buscar registros').fill('no coincide');
  await expect(page.getByRole('heading', { name: 'No encontramos resultados' })).toBeVisible();
  await page.getByRole('button', { name: 'Limpiar filtros' }).click();
  await expect(page.getByLabel('Buscar registros')).toHaveValue('');
  await expect(cell('Bruno')).toBeVisible();
  await expect(cell('Diana')).toBeVisible();
  await page.getByLabel('Sede de solicitud').selectOption(otherClub.id);
  await expect(cell('Bruno')).toBeVisible();
  await expect(cell('Ana')).toHaveCount(0);
  await page.getByRole('button', { name: 'Limpiar filtros' }).click();
  await page.getByLabel('Deporte de solicitud').selectOption(football.id);
  await page.getByLabel('Estado de solicitud').selectOption('RESERVATION_PAID');
  await expect(cell('Bruno')).toBeVisible();
  await expect(cell('Carla')).toBeVisible();
  await expect(cell('Ana')).toHaveCount(0);
  await expect(cell('Elena')).toHaveCount(0);
  await page.getByLabel('Estado de solicitud').selectOption('TOTAL_PAID');
  await expect(cell('Elena')).toBeVisible();
  await expect(cell('Carla')).toHaveCount(0);
  await expect(page.getByRole('cell', { name: /Pagó total/ })).toBeVisible();
  await page.getByLabel('Fecha del turno desde').fill('2099-01-12');
  await page.getByLabel('Fecha del turno hasta').fill('2099-01-10');
  await expect(page.getByRole('alert').filter({ hasText: 'La fecha desde' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Limpiar filtros' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
